Repository elastic/ems-client, pull requests merged in 2020-03, with the labels that each got.

#18 Add appName and appVersion parameters
  README.md
  src/ems_client.js
  test/ems_client.test.js
  test/ems_client_util.js
Labels: v7.7.0

#19 Update dependencies
  yarn.lock
Labels: v7.7.1

#20 Remove node-fetch dependency
  package-lock.json
  package.json
  src/ems_client.js
  test/ems_client_util.js
Labels: 7.7.2
