Repository elastic/ems-client, pull requests merged in 2023-11, with the labels that each got.

#208 Upgrade to Node 20
  .buildkite/pipeline.yml
  .nvmrc
  package.json
Labels: v7.17.1, v8.4.1, v8.5.1

#209 [7.17] Update yarn.lock via upgrade-interactive (#205)
  yarn.lock
Labels: backport

#210 [8.4] Upgrade to Node 20 (#208)
  .buildkite/pipeline.yml
  .nvmrc
  package.json
Labels: backport

#211 [7.17] Upgrade to Node 20 (#208)
  .buildkite/pipeline.yml
  .nvmrc
  package.json
Labels: backport

#213 Release 7.17.1
  CHANGELOG.md
Labels: v7.17.1

#212 Release 8.4.1
  CHANGELOG.md
Labels: v8.4.1

#214 Release EMS Client 8.5.1
  CHANGELOG.md
Labels: v8.5.1

#215 Bump to 8.5.2
  CHANGELOG.md
  package.json
Labels: v8.5.2

#216 Bump to 8.4.2
  CHANGELOG.md
  package.json
Labels: v8.4.2

#217 Bump to 7.17.2
  CHANGELOG.md
  package.json
Labels: v7.17.2
